resources:
- name: ci-repo
  type: git
  source:
    uri: ((repo.uri))
    branch: ((repo.branch))
    private_key: ((repo.ro-key))
    paths:
    - ci/

jobs:
- name: build-ci-image
  plan:
  - get: ci-repo
    params:
      submodules: none
  - task: build
    file: ci-repo/ci/tasks/build-image/task.yml
    input_mapping:
      input: ci-repo
    params:
      NIMBUS_USER: ((ci/nimbus.user))
      BUILD_ARG_BASE: ((dockerhub-proxy))/library/debian:stable-slim
      CONTEXT: input/ci/images/ci-image

- name: build-docker-image
  plan:
  - get: ci-repo
    params:
      submodules: none
  - task: build
    file: ci-repo/ci/tasks/build-image/task.yml
    input_mapping:
      input: ci-repo
    params:
      NIMBUS_USER: ((ci/nimbus.user))
      BUILD_ARG_BASE: devtools-docker.artifactory.eng.vmware.com/vmware/runway/resourcetypes/docker-in-nimbus-task:0.13.0
      CONTEXT: input/ci/images/docker-image
      UNPACK_ROOTFS: true

  - task: test
    image: image
    config:
      platform: linux
      run:
        path: bash
        args:
        - -c
        - |
          exit 1
    params:
      NIMBUS_DEPLOY_OPTS: '--memory=4096 --disk=10485760 --cpus=4'
